### ISSUE TITLE
Sendmail does not works

### ISSUE THREAD

**Issue by nizovtsevnv** [bitnami/bitnami-docker-phabricator#104]
-------------------------------
    BUG REPORT INFORMATION
-------------------------------

**Description**

Proper work of this container needs an email sending functionality but it's not work from the box via sendmail, via providers: PhabricatorMailImplementationPHPMailerLiteAdapter, PhabricatorMailImplementationPHPMailerAdapter.

**Steps to reproduce the issue:**

1. Configure docker-compose.yml (this container + bitnami mariadb) with SMTP setting for gmail.com:
```
version: '2'

services:
  ######################################################################
  mariadb:
    expose:
      - 3306
    volumes:
      - ./data/mariadb:/bitnami/mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    container_name: phabricator-db
    image: 'bitnami/mariadb:latest'
    restart: always
  ######################################################################
  phabricator:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data:/bitnami
    environment:
      - MARIADB_HOST=phabricator-db
      - PHABRICATOR_HOST=https://phabricator
      - PHABRICATOR_EMAIL=my_email@gmail.com
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PASSWORD=MY_SUPER_PASSWORD
      - SMTP_PORT=465
      - SMTP_PROTOCOL=ssl
      - SMTP_USER=my_email@gmail.com
    container_name: phabricator
    image: bitnami/phabricator:latest
    depends_on:
      - mariadb
    restart: always
```
2. Start it with `docker-compose up -d` and log in
3. Add new email address to a user

**Describe the results you received:**

In result welcome email is not send and the log contains:
```
phabricator    | [27-Jul-2018 08:50:53 UTC] [2018-07-27 08:50:53] EXCEPTION: (PhutilProxyException) Error while executing Task ID 100. {>} (CommandException) Command failed with error #127!
phabricator    | COMMAND
phabricator    | /usr/sbin/sendmail -oi -t
phabricator    | 
phabricator    | STDOUT
phabricator    | (empty)
phabricator    | 
phabricator    | STDERR
phabricator    | sh: 1: /usr/sbin/sendmail: not found
phabricator    |  at [<phutil>/src/future/exec/ExecFuture.php:369]
phabricator    | [27-Jul-2018 08:50:53 UTC] arcanist(head=stable, ref.stable=b4ba68b97575), phabricator(head=stable, ref.stable=cc69bed52fb9), phutil(head=stable, ref.stable=47c97f0c4842)
phabricator    | [27-Jul-2018 08:50:53 UTC]   #0 <#2> ExecFuture::resolvex() called at [<phabricator>/externals/phpmailer/class.phpmailer-lite.php:540]
phabricator    | [27-Jul-2018 08:50:53 UTC]   #1 <#2> PHPMailerLite::SendmailSend(string, string) called at [<phabricator>/externals/phpmailer/class.phpmailer-lite.php:499]
phabricator    | [27-Jul-2018 08:50:53 UTC]   #2 <#2> PHPMailerLite::Send() called at [<phabricator>/src/applications/metamta/adapter/PhabricatorMailImplementationPHPMailerLiteAdapter.php:126]
phabricator    | [27-Jul-2018 08:50:53 UTC]   #3 <#2> PhabricatorMailImplementationPHPMailerLiteAdapter::send() called at [<phabricator>/src/applications/metamta/storage/PhabricatorMetaMTAMail.php:619]
phabricator    | [27-Jul-2018 08:50:53 UTC]   #4 <#2> PhabricatorMetaMTAMail::sendWithMailers(array) called at [<phabricator>/src/applications/metamta/storage/PhabricatorMetaMTAMail.php:505]
phabricator    | [27-Jul-2018 08:50:53 UTC]   #5 <#2> PhabricatorMetaMTAMail::sendNow() called at [<phabricator>/src/applications/metamta/PhabricatorMetaMTAWorker.php:22]
phabricator    | [27-Jul-2018 08:50:53 UTC]   #6 <#2> PhabricatorMetaMTAWorker::doWork() called at [<phabricator>/src/infrastructure/daemon/workers/PhabricatorWorker.php:123]
phabricator    | [27-Jul-2018 08:50:53 UTC]   #7 <#2> PhabricatorWorker::executeTask() called at [<phabricator>/src/infrastructure/daemon/workers/storage/PhabricatorWorkerActiveTask.php:171]
phabricator    | [27-Jul-2018 08:50:53 UTC]   #8 <#2> PhabricatorWorkerActiveTask::executeTask() called at [<phabricator>/src/infrastructure/daemon/workers/PhabricatorTaskmasterDaemon.php:22]
phabricator    | [27-Jul-2018 08:50:53 UTC]   #9 PhabricatorTaskmasterDaemon::run() called at [<phutil>/src/daemon/PhutilDaemon.php:219]
phabricator    | [27-Jul-2018 08:50:53 UTC]   #10 PhutilDaemon::execute() called at [<phutil>/scripts/daemon/exec/exec_daemon.php:131]
```
**Describe the results you expected:**

Successful sending of email messages.

**Version**

- Output of `docker version`:

```
docker version
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:09:33 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:07:38 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

- Output of `docker info`:

```
Containers: 13
 Running: 10
 Paused: 0
 Stopped: 3
Images: 37
Server Version: 18.06.0-ce
Storage Driver: btrfs
 Build Version: Btrfs v4.7.3
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: d64c661f1d51c48782c9cec8fda7604785f93587
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-7-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.34GiB
Name: box
ID: RF4Q:ZJX7:V7CL:ISGQ:YBVU:BKHN:IPAW:T5NP:DWT3:A2QF:YFWD:ICC3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: nizovtsevnv
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.21.2, build a133471
docker-py version: 3.3.0
CPython version: 3.6.5
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

See the docker-compose.yml
