### ISSUE TITLE
Phabricator loads incomplete website

### ISSUE THREAD

**Issue by ThePrimus** [bitnami/bitnami-docker-phabricator#110]
Hello,

I am trying to set up Phabricator with nginx and letsencrypt. After trying to setup phabricator it looked like this:
![grafik](https://user-images.githubusercontent.com/1255859/49893626-3251ee80-fe4c-11e8-8745-7380662746b9.png)

Which seems not like the correct look of the website. If I change the ports of phabricator to 8081 and including the APACHE_HTTP_PORT_NUMBER + adding the IP of the server as Host it works by accessing the website with the IP adress+Port but is not working for the domain. Maybe you can help me.

 ```shell
version: '3.5'

services:
  nginx:
      image: jwilder/nginx-proxy:alpine
      container_name: nginx
      labels:
         - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy" # Label needed for Let's Encrypt companion container
      ports:
        - "80:80"
        - "443:443"
      depends_on: 
        - phabricator
      networks:
        - devops
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
        - ./nginx/certs:/etc/nginx/certs:ro
        - ./nginx/vhost.d:/etc/nginx/vhost.d
        - ./nginx/html:/usr/share/nginx/html 
      restart: always
      
  letsencrypt-nginx-proxy-companion:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    container_name: proxy_letsencrypt-nginx-proxy-companion
    networks:
        - devops
    environment:
      - NGINX_PROXY_CONTAINER=nginx
      - NGINX_DOCKER_GEN_CONTAINER=nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html 
    depends_on:
      - nginx

  mariadb: #CHANGING TO OTHER NAME BREAKS IT
   image: 'bitnami/mariadb:latest' 
   container_name: mariadb-phabricator
   environment:
    - ALLOW_EMPTY_PASSWORD=yes
    - MARIADB_PORT_NUMBER=3307
    #- MARIADB_HOST=mariadb-phabricator
   volumes:
   - './mariadb-phabricator:/bitnami'
   restart: always
   networks:
      - devops

  phabricator:
    image: 'bitnami/phabricator:latest'
    container_name: phabricator
    labels:
     kompose.service.type: nodeport
    ports:
      - '8081:80'
      - '8443:443'
    volumes:
      - './phabricator:/bitnami'
    environment:
      - PHABRICATOR_HOST=phabricator.my.site
      #- APACHE_HTTP_PORT_NUMBER=8081
      #- APACHE_HTTPS_PORT_NUMBER=8443
      - NAMI_LOG_LEVEL=trace8
      - MARIADB_PORT_NUMBER=3307   
      - LETSENCRYPT_HOST=phabricator.my.site,www.phabricator.my.site
      - VIRTUAL_HOST=phabricator.my.site,www.phabricator.my.site
      - VIRTUAL_PORT=80
      #- MARIADB_HOST=mariadb-phabricator
    depends_on:
      - mariadb
    restart: always
    networks:
      - devops

networks:
  devops:
    name: devops-network
  ```

**Comment by juan131** [comment]
Hi @ThePrimus 

I was not able to reproduce the issue using the `docker-compose.yaml` below:

```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  phabricator:
    image: 'bitnami/phabricator:latest'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'phabricator_data:/bitnami'
    environment:
      - PHABRICATOR_HOST=phabricator.my.site
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  phabricator_data:
    driver: local
```

See the screenshot:

<img width="1270" alt="screenshot 2018-12-14 at 10 04 12" src="https://user-images.githubusercontent.com/6740773/49993733-c8d6fa80-ff87-11e8-9169-3f058e385aad.png">

Does the problem disappear if you remove the NGINX proxy?
