### ISSUE TITLE
No such configuration key 'metamta.herald.show-hints'

### ISSUE THREAD

**Issue by snugans** [bitnami/bitnami-docker-phabricator#112]
Hi,

**Steps to reproduce the issue:**

1. [First Step]
 Start up a new container with the following **docker-compose.yml**:

```
version: ‘2’

services:
  mariadb:
    image: ‘bitnami/mariadb:latest’
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ‘mariadb_data:/bitnami’
  phabricator:
    image: ‘bitnami/phabricator:latest’
    labels:
      kompose.service.type: nodeport
    ports:
      - ‘80:80’
      - ‘443:443’
    environment:
      - PHABRICATOR_HOST=192.168.41.124
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=xxx@gmail.com
      - SMTP_PASSWORD=xxx 
      - SMTP_PROTOCOL=tls
    volumes:
      - ‘phabricator_data:/bitnami’
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  phabricator_data:
    driver: local
```

**Describe the results you received:**

During the start I get the following log message:

```
Log:
phabric INFO Configuring SMTP…
Error executing ‘postInstallation’: Usage Exception: No such configuration key ‘metamta.herald.show-hints’! Use config list to list all keys.
```

**Describe the results you expected:**

Start of the Phabricator container.

**Additional information you deem important (e.g. issue happens only occasionally):**

Without the SMTP-settings, everything works fine.

**Version**

latest

**Reply from Phabricator**

This configuration option was removed in https://secure.phabricator.com/D19833. This looks like a problem with the Bitnami image.
