### ISSUE TITLE
Usage Exception: Mailer configuration ("smtp-mailer") specifies invalid options for mailer: Parameter 'port' has invalid type. Expected type 'int', got type 'string'.

### ISSUE THREAD

**Issue by silverstorm** [bitnami/bitnami-docker-phabricator#113]
**Description**

Starting the bitnami/phabricator container fails (on clean host) with: Usage Exception: Mailer configuration ("smtp-mailer") specifies invalid options for mailer: Parameter 'port' has invalid type. Expected type 'int', got type 'string'.

**Steps to reproduce the issue:**

1. Use the docker-compose.yml below
2. Docker-compose up

**Describe the results you received:**

```
phabricator_1  | mysql-c INFO  Found MySQL server listening at mariadb:3306
phabricator_1  | mysql-c INFO  MySQL server listening and working at mariadb:3306
phabricator_1  | phabric INFO  Creating Database...
phabricator_1  | phabric INFO  Configuring Phabricator...
phabricator_1  | phabric INFO  Configuring SMTP...
phabricator_1  | Error executing 'postInstallation': Reading value from stdin...
phabricator_1  | Usage Exception: Mailer configuration ("smtp-mailer") specifies invalid options for mailer: Parameter 'port' has invalid type. Expected type 'int', got type 'string'.
phabricator_1  | 
phabricatortest_phabricator_1 exited with code 1
```

**Describe the results you expected:**

A successful start

**Additional information you deem important (e.g. issue happens only occasionally):**

docker-compose.yml:
```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - '/data/phabricator/phabricator_mariadb:/bitnami'
  phabricator:
    image: 'bitnami/phabricator:latest'
    ports:
      - 1080:80
      - 1043:443
    volumes:
      - '/data/phabricator/phabricator_app:/bitnami'
    environment:
      - PHABRICATOR_HOST=phabricator.domain.com
      - PHABRICATOR_USERNAME=User
      - PHABRICATOR_EMAIL=user@domain.com
      - PHABRICATOR_FIRSTNAME=Firstname
      - PHABRICATOR_LASTNAME=Last name
      - SMTP_HOST=mail.domain.com
      - SMTP_PORT=587
      - SMTP_USER=phabricator@domain.com
      - SMTP_PASSWORD=SomePassword
      - SMTP_PROTOCOL=tls
    depends_on:
      - mariadb
```

**Version**

- Output of `docker version`:

```
Client:
 Version:	18.03.0-ce
 API version:	1.37
 Go version:	go1.9.4
 Git commit:	0520e24
 Built:	Wed Mar 21 23:10:06 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.03.0-ce
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	0520e24
  Built:	Wed Mar 21 23:08:35 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```

- Output of `docker info`:

```
Containers: 3
 Running: 1
 Paused: 0
 Stopped: 2
Images: 3
Server Version: 18.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-8-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 23.22GiB
Name: dockerdebug
ID: TS4U:3VSQ:OTJH:T242:6Q2F:AAEZ:UMWF:YJ52:OCRB:QAD4:MKOB:VI7N
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.8.0, build unknown
docker-py version: 1.9.0
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
```
