### ISSUE TITLE
phabricator stuck at configuration

### ISSUE THREAD

**Issue by cooperspencer** [bitnami/bitnami-docker-phabricator#122]
**Description**
Phabricator is stuck at the point "Configuring Phabricator".

**Steps to reproduce the issue:**
This is my docker-compose.yml:
```
  phabricatordb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_EXTRA_FLAGS=--local-infile=0
    volumes:
      - ./phabricatordb:/bitnami
    networks:
      - service

  phabricator:
    image: 'bitnami/phabricator:latest'
    environment:
      - MARIADB_HOST=phabricatordb
    depends_on:
      - phabricatordb
    volumes:
      - phabricator_data:/bitnami
    networks:
      - service

volumes:
  phabricator_data:
    driver: local
```
**Describe the results you received:**
I hang for half an hour at this point:
```
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-phabricator
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-phabricator/issues

nami    INFO  Initializing apache
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing phabricator
phabric INFO  Creating Phabricator system users...
phabric INFO  Creating Phabricator temporary folders...
phabric INFO  Configuring PHP settings...
phabric INFO  Configuring Apache settings...
phabric INFO  Checking connection to database...
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at phabricatordb:3306
mysql-c INFO  MySQL server listening and working at phabricatordb:3306
phabric INFO  Creating Database...
phabric INFO  Configuring Phabricator...
```

**Describe the results you expected:**
I expected it to work.

**Version**

- Output of `docker version`:

```
docker --version
Docker version 18.09.6, build 481bc7715621
```

- Output of `docker info`:

```
Containers: 15
 Running: 9
 Paused: 0
 Stopped: 6
Images: 24
Server Version: 18.09.6
Storage Driver: btrfs
 Build Version: Btrfs v5.1 
 Library Version: 102
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc oci
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: v0.1.4_catatonit (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 5.1.7-1-default
Operating System: openSUSE Tumbleweed
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.713GiB
Name: sweeney
ID: KSZ3:ZSTM:UTTA:C2YU:CF2A:NLFK:EJ6G:7COX:K7DI:ULR4:24GW:NKKJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.24.0, build 0aa5906
docker-py version: 3.7.2
CPython version: 3.7.3
OpenSSL version: OpenSSL 1.1.1c  28 May 2019
```
