### ISSUE TITLE
Error executing 'postInstallation': MySQL command failed to run. Error:   ERROR 1062 (23000) at line 1: Duplicate entry '1' for key 'PRIMARY'

### ISSUE THREAD

**Issue by pangff** [bitnami/bitnami-docker-phabricator#131]
Description

docker version

`Docker version 18.09.7, build 2d0083d`

docker-compose version

`docker-compose version 1.8.0, build unknown`

os

```
LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```

docker-compose.xml  content:

```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_EXTRA_FLAGS=--local-infile=0
    volumes:
      - 'mariadb_data:/bitnami'
  phabricator:
    image: 'bitnami/phabricator:latest'
    ports:
      - '8888:80'
      - '9999:443'
    volumes:
      - 'phabricator_data:/bitnami'
    depends_on:
      - mariadb
    environment:
      - PHABRICATOR_HOST=xxx.xx.com/pha
      - PHABRICATOR_PASSWORD=Password1qaz
volumes:
  mariadb_data:
    driver: local
  phabricator_data:
    driver: local
```

 
run:

`docker-compose  to up -d`

phabricator get error

```

nami    INFO  Initializing apache
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing phabricator
phabric INFO  Creating Phabricator system users...
phabric INFO  Creating Phabricator temporary folders...
phabric INFO  Configuring PHP settings...
phabric INFO  Configuring Apache settings...
phabric INFO  Checking connection to database...
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at mariadb:3306
mysql-c INFO  MySQL server listening and working at mariadb:3306
phabric INFO  Creating Database...
phabric INFO  Configuring Phabricator...
Error executing 'postInstallation': MySQL command failed to run. Error: 
ERROR 1062 (23000) at line 1: Duplicate entry '1' for key 'PRIMARY'
```

**Comment by alemorcuq** [comment]
Hi, @pangff.

I haven't been able to reproduce your issue. Using a similar `docker-compose.yaml` as you, it works.

```yaml
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_EXTRA_FLAGS=--local-infile=0
    volumes:
      - 'mariadb_data:/bitnami'
  phabricator:
    image: 'bitnami/phabricator:latest'
    ports:
      - '8888:80'
      - '9999:443'
    volumes:
      - 'phabricator_data:/bitnami'
    depends_on:
      - mariadb
    environment:
      - PHABRICATOR_HOST=172.17.0.2
      - PHABRICATOR_PASSWORD=Bitnami1234
volumes:
  mariadb_data:
    driver: local
  phabricator_data:
    driver: local
```

However, if I set `PHABRICATOR_HOST=172.17.0.2/pha` to a path, as you do, I get a different error than you:

```
phabricator_1  | Error executing 'postInstallation': Usage Exception: Config option 'phabricator.base-uri' is invalid. The URI must NOT have a path, e.g. 'http://phabricator.example.com/' is OK, but 'http://example.com/phabricator/' is not. Phabricator must be installed on an entire domain; it can not be installed on a path.
```

Can you try installing it with just the host in the `PHABRICATOR_HOST` variable? Do you have any kind of persisted data in your database that may be causing this issue?

Regards,
Alejandro
