### ISSUE TITLE
Invalid password prevents Phabricator from initialising

### ISSUE THREAD

**Issue by flatline-studios** [bitnami/bitnami-docker-phabricator#139]
**Description**
Attempting to run the phabricator image using Docker Desktop with WSL 2 - Ubuntu 18.04.

**Steps to reproduce the issue:**
1. Create a `docker-compose.yml` file with the following contents:

```
version: '3'

networks:
  phabricator_network:
    driver: bridge

services:
  phabricator:
    image: bitnami/phabricator:2020
    container_name: phabricator
    volumes:
      - "S:\\Development\\Docker\\Phabricator\\Phabricator\\data:/bitnami"
    ports:
      - '9090:80'
      - '9443:443'
    environment:
      PHABRICATOR_USERNAME: phabricator
      PHABRICATOR_PASSWORD: phabricator
      PHABRICATOR_FIRSTNAME: Phabricator
      PHABRICATOR_LASTNAME: Admin
      MARIADB_PASSWORD: An-Awesome_Secret
      MARIADB_HOST: phabricator-mariadb
    networks:
      - phabricator_network
    depends_on:
      - phabricator-mariadb
    restart: unless-stopped

  phabricator-mariadb:
    image: mariadb
    container_name: phabricator-mariadb
    command:
      'mysqld --innodb-flush-method=fsync'
    volumes:
      - "S:\\Development\\Docker\\Phabricator\\MariaDB\\data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: An-Awesome_Secret
    networks:
      - phabricator_network
    restart: unless-stopped
```

2. `docker-compose up && docker logs phabricator -f`

3. Watch the world burn...

**Describe the results you received:**

The image fails to run properly, giving a string of different errors when run sequentially:

```
Welcome to the Bitnami phabricator container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-phabricator
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-phabricator/issues
Send us your feedback at containers@bitnami.com

==> Regenerating SSH host keys...
nami    INFO  Initializing apache
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing phabricator
phabric INFO  Creating Phabricator system users...
phabric INFO  Creating Phabricator temporary folders...
phabric INFO  Configuring PHP settings...
phabric INFO  Configuring Apache settings...
phabric INFO  Checking connection to database...
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at phabricator-mariadb:3306
mysql-c INFO  MySQL server listening and working at phabricator-mariadb:3306
phabric INFO  Creating Database...
phabric INFO  Configuring Phabricator...
Error executing 'postInstallation': There was an issue while passing the registration of the admin user. The error was: Error: No BUTTON 'Log Out'

Welcome to the Bitnami phabricator container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-phabricator
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-phabricator/issues
Send us your feedback at containers@bitnami.com

nami    INFO  Initializing phabricator
phabric INFO  Creating Phabricator system users...
phabric INFO  Creating Phabricator temporary folders...
Error executing 'postInstallation': ELOOP: too many symbolic links encountered, lstat '/opt/bitnami/phabricator/logs/.htaccess'

Welcome to the Bitnami phabricator container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-phabricator
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-phabricator/issues
Send us your feedback at containers@bitnami.com

nami    INFO  Initializing phabricator
phabric INFO  Creating Phabricator system users...
phabric INFO  Creating Phabricator temporary folders...
Error executing 'postInstallation': ELOOP: too many symbolic links encountered, lstat '/opt/bitnami/phabricator/logs/.htaccess'

Welcome to the Bitnami phabricator container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-phabricator
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-phabricator/issues
Send us your feedback at containers@bitnami.com

nami    INFO  Initializing phabricator
phabric INFO  Creating Phabricator system users...
phabric INFO  Creating Phabricator temporary folders...
Error executing 'postInstallation': ELOOP: too many symbolic links encountered, lstat '/opt/bitnami/phabricator/logs/.htaccess'

Welcome to the Bitnami phabricator container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-phabricator
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-phabricator/issues
Send us your feedback at containers@bitnami.com

nami    INFO  Initializing phabricator
phabric INFO  Creating Phabricator system users...
phabric INFO  Creating Phabricator temporary folders...
Error executing 'postInstallation': Unable to start com.bitnami.apache: Pid file '/opt/bitnami/apache/tmp/httpd.pid' was found but either no proper PID was found or no process is running there.: Pid file '/opt/bitnami/apache/tmp/httpd.pid' was found but either no proper PID was found or no process is running there.

Welcome to the Bitnami phabricator container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-phabricator
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-phabricator/issues
Send us your feedback at containers@bitnami.com

nami    INFO  Initializing phabricator
phabric INFO  Creating Phabricator system users...
phabric INFO  Creating Phabricator temporary folders...
Error executing 'postInstallation': Unable to start com.bitnami.apache: Pid file '/opt/bitnami/apache/tmp/httpd.pid' was found but either no proper PID was found or no process is running there.: Pid file '/opt/bitnami/apache/tmp/httpd.pid' was found but either no proper PID was found or no process is running there.
```

It carries on restarting and hitting the two errors forever.

**Describe the results you expected:**

The container to get up and running correctly.

**Additional information you deem important (e.g. issue happens only occasionally):**

N/A

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:37 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 4
  Running: 3
  Paused: 0
  Stopped: 1
 Images: 17
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.84-microsoft-standard
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 12.38GiB
 Name: docker-desktop
 ID: GWQ3:7G6S:GFHD:4LST:RCHA:WNXW:YZMO:RBET:5KII:KZKA:AVAH:PL2E
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 67
  Goroutines: 78
  System Time: 2020-03-02T18:43:29.3916641Z
  EventsListeners: 3
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.25.4, build 8d51620a
docker-py version: 4.1.0
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.1c  28 May 2019
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Docker Desktop (Community)
Version: 2.2.1.0 (42746)
Channel: Edge
