### ISSUE TITLE
error 500

### ISSUE THREAD

**Issue by ahmed20391849** [bitnami/bitnami-docker-phabricator#144]
![image](https://user-images.githubusercontent.com/34915846/80222175-588dbe00-863e-11ea-9449-662b667f3ad7.png)
i got this error on my browser after docker-compose up
"This request asked for "/" on host "localhost", but no site is configured which can serve this request."

**Comment by juan131** [comment]
Hi @ahmed20391849 

Phabricator needs to be configured with a resolvable host to work. As you can see in the link below, you can use the environment variable `PHABRICATOR_HOST` to setup the host were you'll be serving Phabricator:

- https://github.com/bitnami/bitnami-docker-phabricator#environment-variables

For instance, you can edit the **docker-compose.yaml** like this:

```diff
diff --git a/docker-compose.yml b/docker-compose.yml
index f3d653c..5fed562 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -14,6 +14,8 @@ services:
       - '443:443'
     volumes:
       - 'phabricator_data:/bitnami'
+    environment:
+      - PHABRICATOR_HOST=phabricator.local
     depends_on:
       - mariadb
 volumes:
```

And add the `phabricator.local` hostname to your `/etc/hosts`:

```console
$ echo "127.0.0.1  phabricator.local" | sudo tee -a /etc/hosts
127.0.0.1  phabricator.local
```

Then, open a browser and go to http://phabricator.local

**Comment by rwarren** [comment]
I have a similar problem, I'm running this container at `foo.mydomain.com:9080`, and have set up `docker-compose.yml` as follows

```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.3'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_EXTRA_FLAGS=--local-infile=0
    volumes:
      - 'mariadb_data:/bitnami'
  phabricator:
    image: 'bitnami/phabricator:2020'
    ports:
      - '9080:80'
      - '9443:443'
    volumes:
      - 'phabricator_data:/bitnami'
    depends_on:
      - mariadb
    environment:
      - PHABRICATOR_HOST=foo.mydomain.com
volumes:
  mariadb_data:
    driver: local
  phabricator_data:
    driver: local
```

I still get the "site not found" problem:

```
Site Not Found
This request asked for "/" on host "edwin.perspexis.com", but no site is configured which can serve this request.
```

What is the correct way to handle this? Might be worth updating the docs as well.

**Comment by juan131** [comment]
Hi @rwarren 

The env. variable ** PHABRICATOR_HOST** is only taken into account the first time you deploy your container. Once they're deployed, the configuration/database is persisted and it's necessary to update the associated setting manually. 

Are you deploying Phabricator on a "clean" environment? I mean, without existing data in the `mariadb_data` and `pharicator_data` volumes from previous deployments.

**Comment by joeySeal** [comment]
I am having a similar issue with the following docker-compose.yml Docker is running on my LAN so I added `10.12.10.200    phab.local` to my workstations hosts file. I get a reply when I ping that address, the docker compose terminal output shows the get request but all I get it "Site not found" when attempting `https://phab.local/phabricator` and `https://phab.local/ `in my browser.

```
version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_EXTRA_FLAGS=--local-infile=0
    volumes:
      - 'mariadb_data:/bitnami'
  phabricator:
    image: 'docker.io/bitnami/phabricator:2020-debian-10'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'phabricator_data:/bitnami'
    depends_on:
      - mariadb
    environment:
      - PHABRICATOR_HOST=phab.local
volumes:
  mariadb_data:
    driver: local
  phabricator_data:
    driver: local
```
