### ISSUE TITLE
Phabricator on DSM 6.1 Synology

### ISSUE THREAD

**Issue by superloopnetwork** [bitnami/bitnami-docker-phabricator#146]
Hi there,

Is there any way we can get this running on our Synology NAS? I can download the image just fine and it creates the containers. However, I have a feeling the volumes and environment variables are incorrect on mine. Please assist if you can...

I've changed the ports in the *.yml file because as someone in the previous thread stated, 443 is in use. I've also changed the directory structure to reflect how Synology was setup... Is this correct?

```
root@SRV:/volume1/docker# ls -lhs | egrep "phab|maria"
   0 drwxr-xr-x+ 1 root   root             0 May 23 09:14 mariadb
   0 drwxr-xr-x+ 1 root   root            22 May 23 09:19 phabricator
```

```
version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_EXTRA_FLAGS=--local-infile=0
    volumes:
      - 'volume1:/docker/mariadb'
  phabricator:
    image: 'docker.io/bitnami/phabricator:2020-debian-10'
    ports:
      - '8888:8888'
      - '4433:4433'
    volumes:
      - 'volume1:/docker/phabricator'
    depends_on:
      - mariadb
volumes:
  volume1:
    driver: local
```
When I run docker-compose....
```
root@SRV:/volume1/docker# docker-compose up -d
Creating volume "docker_volume1" with local driver
Recreating docker_mariadb_1 ... done
Recreating docker_phabricator_1 ... done
```

I have a feeling these may be incorrect?

![image](https://user-images.githubusercontent.com/23246145/82733407-8d467100-9ce1-11ea-941b-6b6f6aedd977.png)

![image](https://user-images.githubusercontent.com/23246145/82733432-aea75d00-9ce1-11ea-9e5d-ac3424e4efd9.png)

![image](https://user-images.githubusercontent.com/23246145/82733448-c7177780-9ce1-11ea-80fb-0181ecc8b6cb.png)

Please help.....
