### ISSUE TITLE
Unable to connect to MYSQL: Error executing 'postInstallation': Failed to connect to mysql:3306 after 36 tries

### ISSUE THREAD

**Issue by Kirito70** [bitnami/bitnami-docker-phabricator#155]
**Description**

I am trying to use *Phabricator* with an external Mysql Container. I am not using bitnami-mariadb container no do I have MySQL container in this compose file either. 

**Steps to reproduce the issue:**

1. Downloaded the compose file
2. Removed mariadb container
3. Updated environment variables
4. Started container

**Describe the results you received:**

```
mysql-c INFO  Trying to connect to MySQL server
Error executing 'postInstallation': Failed to connect to mysql:3306 after 36 tries
```

**Describe the results you expected:**

```
Container should have started correctly and I should be able to access the site.
```

**Additional information you deem important (e.g. issue happens only occasionally):**

```
version: '2'
services:
  phabricator:
    restart: always
    expose:
     - "443"
     - "80"
    volumes:
     - /srv/docker/bitnami-phabricator:/bitnami
    networks:
     - mariadb
     - nginx-proxy
    environment:
     - MARIADB_HOST=mysql
     - MARIADB_PORT_NUMBER=3306
     - MARIADB_USER==root
     - MARIADB_PASSWORD==******
     - PHABRICATOR_USERNAME==******
     - PHABRICATOR_PASSWORD==******
     - PHABRICATOR_EMAIL==******
     - PHABRICATOR_FIRSTNAME==******
     - PHABRICATOR_LASTNAME==******
     - PHABRICATOR_HOST==******
     - SMTP_HOST=******
     - SMTP_PORT=587
     - SMTP_USER=*******
     - SMTP_PASSWORD=******
     - SMTP_PROTOCOL=tls
     - VIRTUAL_HOST=******
    image: bitnami/phabricator


networks:
        mysql:
                external: true

        nginx-proxy:
                external: true
```

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:44 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:15 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 16
  Running: 14
  Paused: 0
  Stopped: 2
 Images: 23
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-42-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.775GiB
 Name: vmi401462.contaboserver.net
 ID: TJ6I:6CMF:BZGF:B77Y:ACM5:CJB2:4ZGX:OO2U:WDCU:NL3E:UDVD:HONL
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.8.2
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

I am using ubuntu 20.04 LTS as operating system.

**Comment by dani8art** [comment]
Hi @Kirito70, did you check that `MARIADB_HOST=mysql` is reachable from the Phabricator container? Can you share how you are deploying the MySQL container?

Thanks!

**Comment by Kirito70** [comment]
Hi @dani8art Thanks for your reply. I am sorry for being late as I was out of the city. Here is the docker-compose file for my MySQL container.  **Mysql version is 8.0**

```
 version: '3.1'

 services:

        db:
                image: mysql
                command: --default-authentication-plugin=mysql_native_password
                container_name: mysql
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: Allah@321
                ports:
                        - 3306:3306
                volumes:
                        - /var/data/mysql:/var/lib/mysql
                networks:
                        - mysql

networks:

        mysql:
                external:
                        name: mysql
```

I also have created external network for mysql as well.
Here is the result of `docker network inspect mysql` 

```
[
    {
        "Name": "mysql",
        "Id": "42b85e5230447f6fd67732e3a471cd5586e8fa0ec4bc37fb32b61ac0c6dbcf56",
        "Created": "2020-08-05T02:31:41.313819189+02:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "172.22.0.0/16",
                    "Gateway": "172.22.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "619594a308dde1f646daf46ff3fd66e51d78d418c769ec520ec25afa56eeb56b": {
                "Name": "mysql",
                "EndpointID": "a9ab90d28d0232398c5adcf97fe6a9c40cb40615d17e1b2ad0b8a7440f116fb8",
                "MacAddress": "02:42:ac:16:00:02",
                "IPv4Address": "172.22.0.2/16",
                "IPv6Address": ""
            },
            "7db6b215549822413e8ac25bf7c276aef163966f69b2cde41a51c982f121269d": {
                "Name": "redmine_redmine_1",
                "EndpointID": "d458c95cdfff4cbb7be9ef7cb9a65c6a935b20e1c686d8c0d38383d1c705f2e4",
                "MacAddress": "02:42:ac:16:00:03",
                "IPv4Address": "172.22.0.3/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {}
    }
]
```

Some other containers are using mysql network as well and they are working fine.

Thanks for your help.
Kind Regards,
MT

**Comment by dani8art** [comment]
Hi @Kirito70 could you try to create a network alias for MySQL in mysql-docker-compose?

``` yaml
        networks:
            mysql:
                aliases: 
                    - mysql
```

**Comment by Kirito70** [comment]
Hi @dani8art I have updated my mysql docker-compose file like this but it didn't work. Can you please guide me on what went wrong?
```
version: '3.1'

services:

        db:
                image: mysql:5.7.32
                command: --default-authentication-plugin=mysql_native_password
                container_name: mysql57
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: *******
                ports:
                        - 3307:3306
                volumes:
                        - /var/data/mysql:/var/lib/mysql
                networks:
                        mysql57:
                                aliases:
                                        - mysql57alias

networks:
        mysql:
                external: true

```

And my phabricator docker-compose file is 

```
version: '2'
services:
  phabricator:
    restart: always
    expose:
     - "443"
     - "80"
    volumes:
     - /srv/docker/bitnami-phabricator:/bitnami
    networks:
     - mysql57alias
     - nginx-proxy
    environment:
     - MARIADB_HOST=mysql57alias
     - MARIADB_PORT_NUMBER=3307
     - MARIADB_USER=*****
     - MARIADB_PASSWORD=*******
     - PHABRICATOR_USERNAME=******
     - PHABRICATOR_PASSWORD=*******
     - PHABRICATOR_EMAIL=******
     - PHABRICATOR_FIRSTNAME=******
     - PHABRICATOR_LASTNAME=******
     - PHABRICATOR_HOST=*******
     - SMTP_HOST=******
     - SMTP_PORT=*****
     - SMTP_USER=******
     - SMTP_PASSWORD=*******
     - SMTP_PROTOCOL=tls
     - VIRTUAL_HOST=********
    image: bitnami/phabricator


networks:
        mysql57alias:
                external:
                        name: mysql57

        nginx-proxy:
                external: true


```

Please have a look
Kind Regards,
MT

**Comment by juan131** [comment]
Hi @Kirito70 

First, we need to discard the issue is not related with some miss-configuration in your network setup. To do so, please modify the Phabricator Docker Compose so you overwrite the default command:

```diff
version: '2'
services:
  phabricator:
+   command: sleep infinity
    restart: always
    ...
```

Doing this, Phabricator won't be initialised and instead, the container will be sleeping forever. Therefore, after you run `docker-compose up`, you can open a shell on the container and check the connectivity:

- Open the shell:

```bash
docker-compose exec phabricator bash
```

- Install dnsutils

```bash
install_packages dnsutils
```

- Run `nslookup` to see if the hostname "mysql57alias" resolves the MySQL container's IP:

```bash
nslookup mysql57alias
```

**Comment by Kirito70** [comment]
@juan131 Thanks for the replay I have just executed `nslookup` and it seems to be resolving the network here is the output. Please have a look

```
Server:		127.0.0.11
Address:	127.0.0.11#53

Non-authoritative answer:
Name:	mysql57alias
Address: 192.168.48.2

```

Please guide me to the next step.

Thanks & Kind Regards,
MT

**Comment by juan131** [comment]
Hi @Kirito70 

Cool, I think we can discard the issue is in the network configuration at this point.

---

Let's try to discard it's related with some incompatibility between the MySQL client included in the PH image and your MySQL image.

Using the same scenario I told you to use to check that `nslookup` could solve the hostname, open a shell again and run the command below:

```console
$ mysql -h $MARIADB_HOST -P $MARIADB_PORT_NUMBER -u$MARIADB_USER -p$MARIADB_PASSWORD
```

**Comment by Kirito70** [comment]
Hi @juan131,

I am using MySQL 5.7 and I have executed the command that you have asked me to run: 

```
ERROR 2002 (HY000): Can't connect to MySQL server on 'mysql57alias' (115)
```

I hope this helps.

Kind Regards,
MT

**Comment by juan131** [comment]
Hi @Kirito70 

I just noticed that you're exposing port 3306 in the Docker Compose for MYSQL:

```
        ports:
          - 3306:3306
```

But you're setting in Phabricator:

```
    environment:
     - MARIADB_HOST=mysql57alias
     - MARIADB_PORT_NUMBER=3307
```

Therefore, you're to connect to wrong port.

**Comment by Kirito70** [comment]
Hi @juan131,
Sorry about the confusion that is Mysql 8.0 container that I was using previously. I can retest it using the previous configuration as well. No, I will just revert it to the previous config and test it again, and will share the result with you.

I am really sorry about the confusion.

**Comment by juan131** [comment]
Hi @Kirito70 

I just noticed you're setting `MARIADB_PORT_NUMBER=3307`:

```yaml
    environment:
     - MARIADB_HOST=mysql57alias
     - MARIADB_PORT_NUMBER=3307
```

But the MySQL serve is running on port **3306**. Please note that when, you do this:

```
services:
  db:
    image: mysql:5.7.32
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql57
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: *******
    ports:
      - 3307:3306
```

You're mapping the port **3307** of your host with the port  **3306** of the container. However, in the Docker Network the port exposed in the container is still **3306**. Therefore, the client on PH needs to use that pot
