### ISSUE TITLE
PHABRICATOR_ENABLE_GIT_SSH_REPOSITORY did not work

### ISSUE THREAD

**Issue by ftiasch** [bitnami/bitnami-docker-phabricator#166]
**Description**

**Steps to reproduce the issue:**

1. Run `docker-compose up -d` with a `docker-compose.yml` as 
```
version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_SQL_MODE=STRICT_ALL_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
      - MARIADB_EXTRA_FLAGS=--local-infile=0 --max-allowed-packet=32M --innodb-buffer-pool-size=256MB
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  phabricator:
    image: 'docker.io/bitnami/phabricator:2021.6.0-debian-10-r0'
    user: root
    ports:
      - '127.0.0.1:8080:8080'
      - '127.0.0.1:2223:2223'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - PHABRICATOR_HOST=127.0.0.1
      - PHABRICATOR_USERNAME=user
      - PHABRICATOR_PASSWORD=password
      - PHABRICATOR_EMAIL=user@example.com
      - PHABRICATOR_ENABLE_GIT_SSH_REPOSITORY=yes
      - PHABRICATOR_SSH_PORT_NUMBER=2223
    volumes:
      - 'phabricator_data:/bitnami/phabricator'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  phabricator_data:
    driver: local
```

2. Add my SSH public key into Phabricator.
3. `ssh -T -p2333 git@127.0.0.1 -vvv` as described in [◉ Diffusion User Guide: Repository Hosting - Troubleshooting SSH](https://secure.phabricator.com/book/phabricator/article/diffusion_hosting/#troubleshooting-ssh)

**Describe the results you received:**

```
OpenSSH_7.4p1 Debian-10+deb9u7, OpenSSL 1.0.2u  20 Dec 2019
debug1: Reading configuration data /root/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug2: resolving "127.0.0.1" port 2223
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to 127.0.0.1 [127.0.0.1] port 2223.
debug1: Connection established.
debug1: permanently_set_uid: 0/0
debug1: identity file /root/.ssh/id_rsa type 1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.4p1 Debian-10+deb9u7
ssh_exchange_identification: Connection closed by remote host
```

**Describe the results you expected:**

Something like `phabricator-ssh-exec: Welcome to Phabricator.`.

**Additional information you deem important (e.g. issue happens only occasionally):**

I tried to resolve the issue by myself.

First of all, manually run of `/usr/sbin/sshd -d -d -d` inside the docker container gives me:
```
debug2: load_server_config: filename /etc/ssh/sshd_config
debug2: load_server_config: done config len = 380
debug2: parse_server_config: config /etc/ssh/sshd_config len 380
debug3: /etc/ssh/sshd_config:6 setting AuthorizedKeysCommand /opt/bitnami/phabricator/resources/sshd/phabricator-ssh-hook.sh
debug3: /etc/ssh/sshd_config:7 setting AuthorizedKeysCommandUser git
debug3: /etc/ssh/sshd_config:8 setting AllowUsers git
debug3: /etc/ssh/sshd_config:13 setting Port 2223
debug3: /etc/ssh/sshd_config:14 setting Protocol 2
debug2: /etc/ssh/sshd_config line 14: Deprecated option Protocol
debug3: /etc/ssh/sshd_config:15 setting PermitRootLogin no
debug3: /etc/ssh/sshd_config:16 setting AllowAgentForwarding no
debug3: /etc/ssh/sshd_config:17 setting AllowTcpForwarding no
debug3: /etc/ssh/sshd_config:18 setting PrintMotd no
debug3: /etc/ssh/sshd_config:19 setting PrintLastLog no
debug3: /etc/ssh/sshd_config:20 setting PasswordAuthentication no
debug3: /etc/ssh/sshd_config:21 setting ChallengeResponseAuthentication no
debug3: /etc/ssh/sshd_config:22 setting AuthorizedKeysFile none
debug3: /etc/ssh/sshd_config:24 setting PidFile /var/run/sshd-phabricator.pid
debug1: sshd version OpenSSH_7.9, OpenSSL 1.1.1d  10 Sep 2019
Could not load host key: /etc/ssh/ssh_host_rsa_key
Could not load host key: /etc/ssh/ssh_host_ecdsa_key
Could not load host key: /etc/ssh/ssh_host_ed25519_key
```
Thus, it seems that the host key is missing.

After `ssh-keygen -A`, subsequent `ssh` causes the `sshd` to fail with 
```
/usr/bin/env: 'php': No such file or directory
AuthorizedKeysCommand /opt/bitnami/phabricator/resources/sshd/phabricator-ssh-hook.sh git failed, status 127
```
That seems to be a recurrent of issue #128. Fix it with `ln -s /opt/bitnami/php/bin/php /usr/local/bin`.

After that, we can successfully ssh. However, `GIT_VERBOSE=1 git push -u origin master` still gives 
```
Environment:
  USER=git
  LOGNAME=git
  HOME=/home/git
  PATH=/usr/local/bin:/usr/bin:/bin:/usr/games
  MAIL=/var/mail/git
  SHELL=/bin/sh
  SSH_CLIENT=172.22.0.1 60728 2223
  SSH_CONNECTION=172.22.0.1 60728 172.22.0.3 2223
  SSH_ORIGINAL_COMMAND=git-receive-pack '/source/test.git'
sudo: a password is required
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I have no idea how to fix it entirely.

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.15
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        99e3ed8919
 Built:             Sat Jan 30 03:17:11 2021
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.15
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       99e3ed8919
  Built:            Sat Jan 30 03:15:40 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 10
  Running: 7
  Paused: 0
  Stopped: 3
 Images: 114
 Server Version: 19.03.15
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.9.0-12-amd64
 Operating System: Debian GNU/Linux 9 (stretch)
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 932MiB
 Name: nanometer-hk
 ID: TOAM:DANH:FBPC:WBYX:QVN6:YHX3:BCQZ:G2UX:2OQ4:JYPN:PH3L:KAGI
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.28.2, build 67630359
docker-py version: 4.4.1
CPython version: 3.7.9
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
