### ISSUE TITLE
Notifications support?

### ISSUE THREAD

**Issue by fdcastel** [bitnami/bitnami-docker-phabricator#56]
There are some plans to offer this out-of-box?

https://secure.phabricator.com/book/phabricator/article/notifications/

(would require Node.js installed)

**Comment by dbarranco** [comment]
Hi @fdcastel 

I've read the documentation you posted above and this would require to add another container with the aphlict server on it.

I have also created internal tasks in order to discuss wether we are going to take action on this.
We will update this thread to notify you.

**Comment by svazzole** [comment]
I'm interested on this issue. I've tried to run another container with aphlict on it (more precisely nasqueron/aphlict) but without success. The aphlict container is logging something like:
`Received message: {"command":"ping","data":null}`
and phabricator cannot connect to client and server. Am I missing something here?

**Comment by dbarranco** [comment]
Hi @svazzole 

Have you tried to create an issue on the Github repository of nasqueron to talk about this issue?

I am afraid that we currently do not support this integration.
Kind regards

**Comment by anatoliyarkhipov** [comment]
Did you have guys any success with that? 🤔

**Comment by andresbono** [comment]
Hi @anatoliyarkhipov, we didn't enable that feature yet.

Check this comment in case it helps: https://github.com/bitnami/bitnami-docker-phabricator/issues/116#issuecomment-470668283.

**Comment by anatoliyarkhipov** [comment]
@andresbono 

Unfortunately no. I fail to proceed further than this command:
```bash
root@87664ca4a6fe:/opt/bitnami/phabricator# su phabricator -c './bin/aphlict start'
/usr/bin/env: 'php': No such file or directory
```

Is there any chance you know what I can do about that error?

**Comment by andresbono** [comment]
Does this alternative command work for you?

```
sudo -u daemon ./bin/aphlict start
```

**Comment by anatoliyarkhipov** [comment]
Yeah, that one worked - I was able to run the server. Still, I wasn't able to connect to it, because I hid the Phabricator container behind an Nginx Proxy with HTTPS, basing on tutorial from this comment - https://github.com/bitnami/bitnami-docker-phabricator/issues/57#issuecomment-283570544. 

But thanks to the link you provided previously, I figured out what I should try to achieve at all and eventually was able to set the things up. Below is a small addition to the guide from https://github.com/bitnami/bitnami-docker-phabricator/issues/57#issuecomment-283570544 for those who will come here later.

- - -

So I assume you've set up Phabricator with Nginx Proxy following the guide above and now you're wondering how to add Aphlict to that setup.

1. Add [Aphlict docker container](https://hub.docker.com/r/nasqueron/aphlict/) to your `docker-compose.yml`:
```yml
  aphlict:
    image: nasqueron/aphlict
    container_name: aphlict

    ports:
      # This is the port to which the browser will connect and so 
      # it must be acessible from the outside.
      - "22280:22280"

    expose:
      # This is the port to which Phabricator will try to connect to
      # to do some admin stuff, and it will be done via Docker
      # internal network, so it's enough to just expose it.
      - 22281

    depends_on:
      # I'm not sure about this. My assumption is that we need to
      # depend on the `proxy` to make sure that the SSL certificates
      # are generated and available when Aphlict starts. I might be
      # wrong and then this line is reundant. 
      - proxy

    volumes:
      # We will need to edit the Aphlict config to point it to the
      # SSL certificates, and for not having to do that on every run
      # of the container, I put it on the host machine and forwarded
      # to the container through the volumes.
      - ./aphlict.custom.json:/opt/phabricator/conf/aphlict/aphlict.custom.json
      
      # Those are the same certificates you use for the Nginx Proxy
      # container. I'm not sure if it's correct to use the same certs
      # for both the Phabricator itself, and the Aphlict server, but
      # browsers are OK with that, so am I.
      - ./certs:/opt/phabricator/conf/aphlict/certs:ro

    networks:
      # Again, I'm not sure if it's needed, but my assumption that it
      # is for Phabricator to be able to connect to Aphlict thought
      # the Docker private network.
      - private
```

2. Create `./aphlict.custom.json` with the following content, and replace `YOUR_DOMAIN` with the one you used following the original guide. Like, if you set `$SITE_URL` to `example.ltd` in the original guide, then replace `YOUR_DOMAIN` with `example.ltd` as well.
```json
{
  "servers": [
    {
      "type": "client",
      "port": 22280,
      "listen": "0.0.0.0",
      "ssl.key": "/opt/phabricator/conf/aphlict/certs/YOUR_DOMAIN/key.pem",
      "ssl.cert": "/opt/phabricator/conf/aphlict/certs/YOUR_DOMAIN/fullchain.pem"
    },
    {
      "type": "admin",
      "port": 22281,
      "listen": "0.0.0.0",
      "ssl.key": null,
      "ssl.cert": null
    }
  ],
  "logs": [
    {
      "path": "/var/log/aphlict.log"
    }
  ],
  "pidfile": "/var/run/aphlict.pid"
}
```

3. Do `docker-compose up -d`, proceed to the notifications settings in Phabricator and put there the following config. As with the previous one replace `YOUR_DOMAIN` with your domain. Also, take a note, that you shouldn't change `host` for the  `admin` config - `aphlict` is correct, since it's the name of container in `docker-compose.yml`, and so that host is available within the Docker internal network.
```json
[
  {
    "type": "client",
    "host": "YOUR_DOMAIN",
    "port": 22280,
    "protocol": "https"
  },
  {
    "type": "admin",
    "host": "aphlict",
    "port": 22281,
    "protocol": "http"
  }
]
```

- - -

That's it.
