### ISSUE TITLE
cannot acess

### ISSUE THREAD

**Issue by xiaoxinyi** [bitnami/bitnami-docker-phabricator#71]
```
This request asked for "/" on host "10.65.0.222", 
but no site is configured which can serve this request.
```

`docker-compose.yml`:

```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  phabricator:
    image: 'bitnami/phabricator:latest'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'phabricator_data:/bitnami/phabricator'
      - 'apache_data:/bitnami/apache'
      - 'php_data:/bitnami/php'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  phabricator_data:
    driver: local
  apache_data:
    driver: local
  php_data:
    driver: local
```

**Comment by twoeo** [comment]
The same problem. Can not access just after install.

**Comment by chipironcin** [comment]
@twoeo can you please provide more information following this template?

**Description**



**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**



**Describe the results you expected:**



**Additional information you deem important (e.g. issue happens only occasionally):**



**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by javsalgar** [comment]
Hi, 

If you are not accessing via localhost, then you need to set the `PHABRICATOR_HOST` environment variable in your Dockerfile. Let us know if that fixes the issue.

**Comment by vorou** [comment]
I set the var, but it didn't help. Here's my `docker-compose.yml`:

```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  phabricator:
    image: 'bitnami/phabricator:latest'
    environment:
      - PHABRICATOR_HOST=10.217.8.127
    labels:
      kompose.service.type: nodeport
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'phabricator_data:/bitnami/phabricator'
      - 'apache_data:/bitnami/apache'
      - 'php_data:/bitnami/php'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  phabricator_data:
    driver: local
  apache_data:
    driver: local
  php_data:
    driver: local
```

I've tried both IP and domain name  (`http://elba-phb.dev.kontur.ru/` or `elba-phb.dev.kontur.ru`). Neither of it works, I still get the same error message as thread author.

Do I need to restart something after I modify `docker-compose`? I just stop it with CTRL+C and run `docker-compose up`, is it enough?
