### ISSUE TITLE
phabricator.base-uri not getting set

### ISSUE THREAD

**Issue by chjohnst** [bitnami/bitnami-docker-phabricator#84]
Attempting to start up the container with the following flags and I noticed the base-uri is not getting set in the local.json.

# docker run -d  --name phabricator -p 80:80 --network phabricator --volume phabricator_data:/bitnami --env PHABRICATOR_HOST=http://phabricator bitnami/phabricator:latest

"phabricator.base-uri": "http://127.0.0.1",

**Comment by juan131** [comment]
Hello @chjohnst 

I was unable to reproduce the issue you mentioned. I basically edit the `docker-compose.yml` file adding the lines below and I run `docker-compose up`:

```
    environment:
      - PHABRICATOR_HOST=phabricator.example.com
```

Then I connected to the Docker Container running `docker exec -it bitnamidockerphabricator_phabricator_1 bash` and I run the command below:

```
$ cat /bitnami/phabricator/conf/local/local.json | grep base-uri
  "phabricator.base-uri": "http://phabricator.example.com",
```

As you can see the **base-uri** was updated as expected.

**Comment by ermik** [comment]
Same issue with a docker-compose:
`  - PHABRICATOR_HOST=phab.local.domain.ai`

almost all environment variables are customized (mail, username, etc)

went into container manually and changed the config for the time being. Another question is, does this affect system hosts file? If there is a base-uri set on a local machine, what is the right way to get it working?

**Comment by juan131** [comment]
Hi @ermik 

It does not affect the System Hosts files, it only affects to the Phabricator configuration files. You can use the "config" command to set the Base Uri, for instance:

```
/opt/bitnami/phabricator/bin/config set phabricator.base-uri http://my-example-domain.com
```

**Comment by ermik** [comment]
Since there is "configuration as code" here, couldn't we use the same config values to set up the entire container, not just Phabricator env?

Or am I not getting something?

**Comment by juan131** [comment]
Why do you want to modify the container environment? I mean, Phabricator will use its own configuration(**/bitnami/phabricator/conf/local/local.json**) to configure the hostname so I don't see any reason to modify the container environment.

**Comment by ermik** [comment]
When the container spins up, for the first time, Phabricator is not being set up properly. That's a fact — no matter how many times I tried to repeat it. The expectation is that values from the Dockerfile will make it into Phabricator configuration (mail config, url config, etc.). Currently, it doesn't work that way. I honestly don't know why. 😄

**Comment by juan131** [comment]
That's so weird since I could configure the hostname using the `PHABRICATOR_HOST` environment variable. Are you using the latest version of this Docker Image? Could you please run `docker pull` to ensure you're running the latest version?

```
docker pull bitnami/phabricator
```

**Comment by ermik** [comment]
Using the latest version, and just following the instructions in README and adding custom hostname & mail settings does (re-)produce the problem. I am looking into what could go wrong, but just recently tried it on a clean machine (Mac) and it's broken there too.

Will keep trying to find what's up and if I find anything I'll make a PR.

**Comment by juan131** [comment]
Hi @ermik 

Could you share the `docker-compose.yml` file you're using? I just want to double-check it.

**Comment by ermik** [comment]
```yaml
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  phabricator:
    image: 'bitnami/phabricator:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'phabricator_data:/bitnami'
    environment:
      - PHABRICATOR_HOST: 'example.com'
      - PHABRICATOR_USERNAME: 'ermik'
      - PHABRICATOR_PASSWORD: 'hey1234'
      - PHABRICATOR_EMAIL: 'email@ermolay.com'
      - PHABRICATOR_FIRSTNAME: 'Ermolay'
      - PHABRICATOR_LASTNAME: 'Romanov'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  phabricator_data:
    driver: local
```
