### ISSUE TITLE
Helm chart has no way to set `$_SERVER['HTTPS'] = true;`

### ISSUE THREAD

**Issue by sammerry** [bitnami/bitnami-docker-phabricator#90]
**Description**
Im not sure if this is the most appropriate place for this, but it looks like the helm install for this container cant run behind a revers proxy in kubernetes.
https://github.com/kubernetes/charts/issues/3364

**Steps to reproduce the issue:**

See steps to reproduce in the helm chart ticket
https://github.com/kubernetes/charts/issues/3364
I'm not sure if I've missed an elegant solution for this.

**Describe the results you received:**

When placed behind a reverse proxy in kubernetes using the helm chart. There is no way to set the `$_SERVER['HTTPS'] = true;` value in the preamble file.

**Describe the results you expected:**
It would be great to use a configmap as a volume to mount the value in the correct location.

**Comment by javsalgar** [comment]
Hi,

Could you let us know how you configured the reverse proxy? For example, in Apache, wouldn't something like this work?

```
ProxyPass / http://phabricatior
ProxyPassReverse / http://phabricator
```

It would be something like this

```
Client --> Reverse Proxy (HTTPS) --> Phabricator (HTTP)
                                                         <--
```

**Comment by sammerry** [comment]
Helm is kubernetes specific. In this case I'm using nginx-ingress as the reverse proxy and kube-lego to manage ssl certificates. This is my config. Nginx is terminating ssl and I'm running into the problem they describe here.

https://secure.phabricator.com/book/phabricator/article/configuring_preamble/

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: phab-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'true'
    kubernetes.io/force-ssl-redirect: 'true'
    kubernetes.io/ingress.global-static-ip-name: ingress-ip
spec:
  rules:
  - host: phab.example.com
    http:
      paths:
      - backend:
          serviceName: phab-phabricator
          servicePort: 80
  tls:
  - secretName: phab-tls-cert
    hosts:
    - phab.example.com
```
