### ISSUE TITLE
Error executing 'postInstallation': Program exited with exit code 1

### ISSUE THREAD

**Issue by cdoco** [bitnami/bitnami-docker-phabricator#91]
**Description**

docker-compose.yml

```
version: '2'
services:
  phabricator:
    image: bitnami/phabricator:latest
    labels:
      kompose.service.type: nodeport
    ports:
      - '7090:80'
      - '7443:443'
    environment:
      - PHABRICATOR_HOST=127.0.0.1
      - PHABRICATOR_USERNAME=admin
      - PHABRICATOR_PASSWORD=admin
      - PHABRICATOR_EMAIL=phabricator@admin.com
      - PHABRICATOR_FIRSTNAME=W
      - PHABRICATOR_LASTNAME=Z
      - MARIADB_USER=root
      - MARIADB_PASSWORD=root
      - MARIADB_HOST=127.0.0.1
      - MARIADB_PORT_NUMBER=3306

      - SMTP_HOST=
      - SMTP_PORT=
      - SMTP_USER=
      - SMTP_PASSWORD=
    volumes:
      - /data/docker/phabricator/data:/bitnami
```

**Describe the results you expected:**

```
Creating phabricator_phabricator_1 ... done
Attaching to phabricator_phabricator_1
phabricator_1  |
phabricator_1  | Welcome to the Bitnami phabricator container
phabricator_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-phabricator
phabricator_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-phabricator/issues
phabricator_1  | Send us your feedback at containers@bitnami.com
phabricator_1  |
phabricator_1  | nami    INFO  Initializing apache
phabricator_1  | apache  INFO  ==> Reconfiguring PID file location...
phabricator_1  | nami    INFO  apache successfully initialized
phabricator_1  | nami    INFO  Initializing php
phabricator_1  | nami    INFO  php successfully initialized
phabricator_1  | nami    INFO  Initializing phabricator
phabricator_1  | phabric INFO  Creating Phabricator system users...
phabricator_1  | phabric INFO  Creating Phabricator temporary folders...
phabricator_1  | phabric INFO  Configuring Apache settings...
phabricator_1  | phabric INFO  Configuring PHP settings...
phabricator_1  | phabric INFO  Checking connection to database...
phabricator_1  | mysql-c INFO  Trying to connect to MySQL server
phabricator_1  | mysql-c INFO  Found MySQL server listening at 127.0.0.1:3306
phabricator_1  | mysql-c INFO  MySQL server listening and working at 127.0.0.1:3306
phabricator_1  | phabric INFO  Creating Database...
phabricator_1  | phabric INFO  Configuring Phabricator...
phabricator_1  | Error executing 'postInstallation': Program exited with exit code 1
phabricator_phabricator_1 exited with code 1
```

**Version**

- Output of `docker version`:

```
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:03:51 2017
 OS/Arch:       darwin/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:12:29 2017
  OS/Arch:      linux/amd64
  Experimental: true
```

- Output of `docker info`:

```
Containers: 17
 Running: 0
 Paused: 0
 Stopped: 17
Images: 9
Server Version: 17.12.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 139
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.60-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: P462:2JZI:7EAF:GHML:6VWX:K7E5:OSDM:KAEL:PJZO:2FCZ:LWAW:CN4Q
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 22
 Goroutines: 41
 System Time: 2018-01-19T04:41:45.212704632Z
 EventsListeners: 2
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 10.100.20.111:5000
 192.168.6.92:5000
 127.0.0.0/8
Registry Mirrors:
 http://192.168.6.92:5000/
 http://10.100.20.111:5000/
Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.18.0, build 8dd22a9
docker-py version: 2.6.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
