### ISSUE TITLE
Site Not Found This request asked for "/" on host "192.168.1.12", but no site is configured which can serve this request.

### ISSUE THREAD

**Issue by isathish** [bitnami/bitnami-docker-phabricator#94]
Site Not Found
This request asked for "/" on host "192.168.1.12", but no site is configured which can serve this request.

**Comment by tompizmor** [comment]
Hi @isathish, 

Could you try again setting the PHABRICATOR_HOST environment variable to that IP address?

```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  phabricator:
    image: 'bitnami/phabricator:latest'
    environment:
      - PHABRICATOR_HOST=192.168.1.12
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'phabricator_data:/bitnami'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  phabricator_data:
    driver: local
```
