### ISSUE TITLE
Port Redirecting Problem

### ISSUE THREAD

**Issue by CarLoOSX** [bitnami/bitnami-docker-phabricator#95]
Hello I have tried to use these ports on my docker-compose :

    ports:
      - '8081:8081'
      - '443:443' 

But I'm not able to access via browser to Phabricator: 

When I try these ports I can access but with some issues:

    ports:
      - '8081:80'
      - '443:443' 

OK. When I access via port 8081 really I'm accessing to port 80 con my container.

But when I'm on login screen and it redirects me to /auth/ my browser rewrites the port 8081 to 80 so I can't see anything.

After I rewrite manually the port to 8081 after 2 o 3 pages I can access to Phabricator's  welcome page and then after navigating inside Phabricator I don't have this problem. 

Any solution/correction ?

Why I can't use these ports?:
    ports:
      - '8081:8081'

What I'm doing wrong ??

Thank you so much .

**Comment by CarLoOSX** [comment]
I have see in apache /bitnami/apache/conf/httpd.conf this:

Listen 80

**Comment by CarLoOSX** [comment]
And this in /bitnami/apache/conf/vhosts/phabricator-vhost.conf : 

<VirtualHost  127.0.0.1:80  _default_:80>

**Comment by juan131** [comment]
> Why I can't use these ports?:
> ports:
> - '8081:8081'

As you mentioned, Apache is configured to listen on the port 80 internally.  Therefore, you cannot use '8081:8081'. 

On the other hand, when you used `'8081:80'` Phabricator is doing some redirections to the port 80 since the base-uri, it's not properly configured. In order to use that configuration, please run:

```
docker-compose exec phabricator /opt/bitnami/phabricator/bin/config set phabricator.base-uri http://127.0.0.1:8080
```

That will solve the issue of the redirections.

**Comment by CarLoOSX** [comment]
Hello!! now is working like a charm !

But ... This is really a problem, right? Will it be fixed in a new version?

Thank you !

**Comment by juan131** [comment]
Great @CarLoOSX 

Yes, I created a task to fix this and included it in our backlog. As the impact of the issue is moderate, there are no immediate plans to work on it. Nevertheless it will be considered for future application versions.

In the meantime you can use the workaround provided on my previous message.

We will update this issue as soon as we have more news.

**Comment by CarLoOSX** [comment]
Hola Juan !

Perfecto me mantendré al tanto ! 

Un saludo 💃

**Comment by tompizmor** [comment]
It is possible to make Phabricator work with these ports in the docker-compose:

```
ports:
  - '8081:8081'
  - '8443:8443' 
```

But you need to tell Apache to run on port 8081 inside the container. For that you can use this env var:

```
APACHE_HTTP_PORT_NUMBER=8081
APACHE_HTTPS_PORT_NUMBER=443
```

The whole docker-compose file would look like this:

```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  phabricator:
    image: 'bitnami/phabricator:2018'
    environment:
      - PHABRICATOR_HOST=YOUR_PHABRICATOR_HOST # defaults to 127.0.0.1
      - APACHE_HTTP_PORT_NUMBER=8081
      - APACHE_HTTPS_PORT_NUMBER=8443
    ports:
      - '8081:8081'
      - '8443:8443'
    volumes:
      - 'phabricator_data:/bitnami'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  phabricator_data:
    driver: local
```

Remember to update the placeholder YOUR_PHABRICATOR_HOST by a real value.
