### ISSUE TITLE
Can't connect to MySQL on fresh install

### ISSUE THREAD

**Issue by GarethFox** [bitnami/bitnami-docker-phabricator#98]
**Description**
It's been several days I try to add a phabricator setup to a custom docker-compose stack services behind nginx-companion.
I could not enter the login page after fresh install and running:
```
CONFIG="docker exec phabricator /opt/bitnami/phabricator/bin/config"
$CONFIG set phabricator.base-uri https://phabricator.example.com
$CONFIG set security.require-https 'true'
docker-compose restart phabricator
```
Result was landind to a 502 bad gateway after the bitnami first connection install page whereas I was able to access other services proxied by nginx-companion.

Facing difficulties, I tried to isolate the setup to the minimum I expect.
This means nginx-companion to proxy phabricator.

I just can't get a connection working between phabricator and mariadb containers on first instance.

**Steps to reproduce the issue:**

1- docker-compose.yml
```
version: '2'

services:
  proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /docker/nginx/vhost.d:/etc/nginx/vhost.d
      - /docker/nginx/certs:/etc/nginx/certs:ro
      - /docker/nginx/html:/usr/share/nginx/html
    networks:
      - public

  proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: proxy-companion
    volumes:
      - /docker/nginx/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - proxy

  mariadb:
    image: bitnami/mariadb:latest
    container_name: mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - /docker/mariadb:/bitnami
    networks:
      - private

  phabricator:
    image: bitnami/phabricator:latest
    container_name: phabricator
    labels:
      kompose.service.type: nodeport
    volumes:
      - /docker/phabricator:/bitnami
    environment:
      - VIRTUAL_HOST=phabricator.example.com
      - LETSENCRYPT_HOST=phabricator.example.com
      - LETSENCRYPT_EMAIL=user@mail.com
      - PHABRICATOR_HOST=phabricator.example.com
    depends_on:
      - mariadb
    expose:
      - 80
    networks:
      - public
      - private

networks:
  public:
  private:
```
2- docker-compose up -d
3- docker-compose logs -f phabricator

**Describe the results you received:**

4- output I have is:
```
mysql-c INFO  Trying to connect to MySQL server
Error executing 'postInstallation': Failed to connect to mariadb:3306 after 36 tries
```

**Describe the results you expected:**
I was expecting to have a working phabricator setup behind a nginx-companion proxy

**Version**

- Output of `docker version`:

```
Client:
 Version:       18.03.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    0520e24
 Built: Wed Mar 21 23:10:06 2018
 OS/Arch:       linux/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.03.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   0520e24
  Built:        Wed Mar 21 23:08:35 2018
  OS/Arch:      linux/amd64
  Experimental: false

```

- Output of `docker info`:

```
Containers: 4
 Running: 2
 Paused: 0
 Stopped: 2
Images: 5
Server Version: 18.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-6-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.91GiB
Name: vps176383
ID: PWWS:OQFV:X6IQ:P46U:FX2C:BTCT:FMPU:M353:XRON:N2TT:VN5F:4B6N
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.21.0-rc1, build 1d32980
docker-py version: 3.2.1
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.1t  3 May 2016

```
